spring.application.name=movieweb
spring.mvc.servlet.path=/api/v1

# ----------------------------------------
# JWT configuration
# ----------------------------------------
jwt.secret=3bdb7e2e49f55b0bb3be4a574b2366794d02705e9e0de98b1a89a009ac2fa26084f622bad6e21e8195f4bfa6b232837d91f4099dd9d3081d7de99be3779886d3860393eca58d8ed3bf6e19cd26f928e5dc644e9be715940ede2c0b1a8d81447e06fc59feb81b04f070411c4c9c43d622f14a879213df32d04fa691812dcd4179
jwt.expiration=86400000  # 1 ngày (??n v?: mili giây)


# ----------------------------------------
# DATABASE CONFIGURATION
# ----------------------------------------
#spring.datasource.url=jdbc:postgresql://<your-host>.neon.tech/<your-database>
#spring.datasource.username=<your-username>
#spring.datasource.password=<your-password>
#spring.datasource.driver-class-name=org.postgresql.Driver


# ----------------------------------------
# DATABASE CONFIGURATION (LOCAL)
# ----------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/movies-web
spring.datasource.username=postgres
spring.datasource.password=2427837
spring.datasource.driver-class-name=org.postgresql.Driver


# ----------------------------------------
# JPA / HIBERNATE CONFIG
# ----------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
server.error.include-message=always